CREATE TABLE PESSOA (
  ID                 BIGINT       NOT NULL AUTO_INCREMENT,
  NOME_COMPLETO      VARCHAR(100) NOT NULL,
  EMAIL              VARCHAR(64)  NOT NULL,
  DATA_NASCIMENTO    VARCHAR(10)  NOT NULL,
  CONSTRAINT PK_USUARIO PRIMARY KEY (ID),
  CONSTRAINT UC_USERNAME UNIQUE (USERNAME)
);
